add policy explorer filters to url and use them to save navigation
EyeSeeTea/uhcpw pull request #109
Opened 2023-08-30 09:24 UTC by davidbgomes

Related to task: [Policy Explorer "History"](https://app.clickup.com/t/865ctwkk0)

- Save policy explorer filters on url and use them to set filters after navigation history changes

2023-09-04 09:02 UTC, davidbgomes commented
Thank you @anagperal ! Oh right, since it was disabled I didn't pay attention to that important part, fixed it :)

2023-09-05 06:19 UTC, xurxodev requested changes
thanks @davidbgomes 

According to the task description, the client wants to navigate to previous filters in policy explorer page when click on back button in the browser. Currently, if you click on navigate after select filters back to home.
I think the problem is that you are using history.replace instead of history.push.

- I've added some minor issue in the code
- We should add some tests to validate parameters in url after changes in filters and after click on back

2023-09-05 06:19 UTC, xurxodev commented on src/webapp/pages/policy-explorer/usePolicyExplorer.ts
> +    useEffect(() => {
to avoid problems with renderers, better split this useEffect in two. One for categories and other for years

2023-09-07 15:21 UTC, davidbgomes commented
Thanks @xurxodev! I've added the tests about the URL and splitted the useEffect logic.

About navigating the filters I thought they meant only if they went outside of the policy explorer page and back, the way they wrote it is kind of ambiguous but I've made those changes, now on every back or forward the filters are changing according to the page history.

2023-09-08 07:00 UTC, xurxodev requested changes
thanks @davidbgomes 

This approach that you are used is not the correct way to test search params in URL. I've investigated, and I created a new branch with a solution.

Please bring changes in feature/policy-explorer-filters-url-jorge to this branch.

2023-09-08 09:44 UTC, davidbgomes commented
Thanks @xurxodev , that's way better, I wasn't able to find a way to use history and resorted to that workaround.

I've also re-added the changes on Router & PolicyExplorerPage to send the history's search to the page, in order to update the filters when a new search param is introduced (when going back or forward on the browser)

2023-09-11 06:14 UTC, xurxodev approved these changes
thanks @davidbgomes

2023-09-14 05:21 UTC, xurxodev approved these changes

2023-09-18 18:03 UTC, merged