Country Page - fetch country resources & expert, code refactor, tests
EyeSeeTea/uhcpw pull request #70
Opened 2023-06-19 13:57 UTC by davidbgomes

[Turn static country page into dynamic one: resources and expert sections](https://app.clickup.com/t/865chqecc)

- created the country page test and added some base tests;
- fetched country resources, with new hook;
- fetched country experts, with new hook;
- Refactored some rushed code.

2023-06-23 05:43 UTC, xurxodev requested changes
thanks @davidbgomes 

Great work in this PR, congratulations!

I've found only an issue to fix and I've added it in comments

2023-06-26 10:15 UTC, davidbgomes commented
Thank you @xurxodev! The pair programming helped a lot to get started with the tests. I've corrected the Person type as well, should be good now. Thanks!

2023-06-26 10:15 UTC, davidbgomes commented on src/domain/entities/Person.ts
> +    countryName?: string;
thanks for the explanation, I must have added for a type error and never corrected it.

2023-06-27 06:20 UTC, xurxodev requested changes
thanks @davidbgomes 

The Typescript check is failing in the last commit.

You can review executing locally:
yarn tsc

2023-07-10 09:31 UTC, davidbgomes commented
Thank you @xurxodev , sorry for the delay.. missed the notification for your review comment. Should be good now!

2023-07-10 10:38 UTC, xurxodev approved these changes
thanks @davidbgomes

2023-08-02 19:01 UTC, merged