change dropdown clear when doesn't have label
EyeSeeTea/uhcpw pull request #71
Opened 2023-06-20 10:12 UTC by davidbgomes

[Design: "Clear all" styles in resources should be the same as in policy explorer](https://app.clickup.com/t/865cg674b)

<img width="1453" alt="image" src="https://github.com/EyeSeeTea/uhcpw/assets/44171664/3d7b9ede-d5f2-4025-bb63-9a0fdc3f65a5">

2023-06-22 11:28 UTC, xurxodev requested changes
thanks @davidbgomes 

I have minor comments to fix in the code

2023-06-22 11:28 UTC, xurxodev commented on src/webapp/components/dropdown/Dropdown.tsx
> +const ClearButton = styled(Button)<{ hasLabel: boolean }>`
I think is clearest name this prop top

2023-06-22 11:28 UTC, xurxodev commented on src/webapp/components/dropdown/Dropdown.tsx
> +    top: ${props => !props.hasLabel && "-30px"};
Top css prop is duplicated and confuse. I think we unify setting parameter prop or 0

2023-06-22 11:28 UTC, xurxodev commented on src/webapp/components/dropdown/Dropdown.tsx
> +                    <ClearButton variant="text" onClick={handleClear} hasLabel={!!label}>
I think would be clearest if we set a top property and here set the logic to pass -30 if label is undefined

2023-06-26 10:27 UTC, davidbgomes commented
Thank you for the review @xurxodev, I've made the changes to use the top prop instead. Should be good now.

2023-06-27 06:16 UTC, xurxodev approved these changes
thanks @davidbgomes

2023-07-31 10:16 UTC, merged