Resources: Tags as theme filter
EyeSeeTea/uhcpw pull request #73
Opened 2023-06-21 12:19 UTC by davidbgomes

[Link resource tags to corresponding resources categories](https://app.clickup.com/t/865cjftra)

<img width="1482" alt="image" src="https://github.com/EyeSeeTea/uhcpw/assets/44171664/378ed33f-e7a6-4000-971b-ead75b4af008">

2023-06-22 11:42 UTC, xurxodev requested changes
thanks @davidbgomes 

I think here there was a misunderstanding. I think this feature should be:
When you click on a theme on comparative analysis, the app should navigate to comparative analysis item filtering by theme.

You have an example of this behaviour to click on a flag (country analysis) on this page then the app navigates to the country analysis filtering by the selected country.

@saragilcas can you confirm that I'm right?

2023-06-27 06:54 UTC, saragilcas commented
Hi, @davidbgomes it is exactly as @xurxodev says, although his example is not working right now. Let me know if you still have doubts,

2023-07-11 06:47 UTC, xurxodev requested changes
thanks @davidbgomes 

Please apply the last changes in the PR https://github.com/EyeSeeTea/uhcpw/pull/74 here because the feature is equal but for different param:
* Sync URL with theme dropdown
* Cancel request in useEffect (review is working because is the same custom hook)

2023-07-12 11:08 UTC, xurxodev requested changes
thanks @davidbgomes 

Some issues to review, I've added comments in the code

2023-07-24 09:27 UTC, davidbgomes commented on src/webapp/components/resources/common/AnalysisItem.tsx
> +            history.push(`/resources/comparative-analysis?theme=${analysisResource.theme}`);
Thank you Jorge, I've fixed that part where clicking on a country-analysis tag leads you to comparative-analysis, we had a meeting and Sara confirmed that the tags on country-analysis should also be a filter, so it's done on both.

2023-07-31 10:05 UTC, merged