fix flag link in resources
EyeSeeTea/uhcpw pull request #74
Opened 2023-06-22 12:31 UTC by davidbgomes

[Contries flags from resources landing Page should be linked to each country](https://app.clickup.com/t/865cjfu6e)

- Fix filters & flag link

2023-06-23 04:41 UTC, xurxodev requested changes
thanks @davidbgomes 

I have found some issues to review, I've added comments in the code

2023-06-23 04:41 UTC, xurxodev commented on src/webapp/components/resources/resources-filters/ResourcesFilters.tsx
> +                filters.country.onSelectedChange([]);
This is a presentation logic and should be in the hooks

2023-06-23 04:41 UTC, xurxodev commented on src/webapp/pages/resources/by-type/useResourcesByType.ts
> +    const [selectedCountry, setSelectedCountry] = useState<string[] | undefined>([""]);
It's confusing and dangerous to have two states fo the country selected: selectedCountry here and filter.country.selected
I think should found the solution to have only the filter.country.selected

2023-06-26 14:01 UTC, davidbgomes commented
Thank you for the review @xurxodev. I wasn't able to make it work without those points that you stated above.

- On the first one I moved from the hook so the selected country appears on the dropdown (otherwise it would re-render and never show it)

- On the second point it would for some reason reset the `filters.country.selected` on some occasions, I would guess some race condition but using a separate state worked.

Maybe we can look at it together?

2023-07-11 06:40 UTC, xurxodev commented
@davidbgomes Finally I fixed the problems in this PR:
I have realized two fixes:
* Sync country param with countries selection in dropdown in two directions
* Fix overlapping request: this was the problem because sometimes the filter doesn't works. I use cancel of futures top avoid overlapping

Please apply the solution in this PR in https://github.com/EyeSeeTea/uhcpw/pull/73

2023-07-11 06:40 UTC, xurxodev approved these changes
thanks @davidbgomes

2023-07-11 10:23 UTC, davidbgomes commented
Thanks for the explanation @xurxodev , nice to know for the future (no pun intended). I also tested and works great. Already applied the solution for the theme PR.

2023-07-31 13:37 UTC, merged